name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
          
      - name: Publish .NET Core Project
        run: dotnet publish BlazorToDoWASM.csproj -c Release -o release --nologo
      
      - name: Adjust index.html
        run: |
          if [ -f "release/wwwroot/index.html" ]; then
            sed -i 's|<base href="/" />|<base href="/BlazorToDoWASM/" />|g' release/wwwroot/index.html
          elif [ -f "release/index.html" ]; then
            sed -i 's|<base href="/" />|<base href="/BlazorToDoWASM/" />|g' release/index.html
          fi
      
      - name: Create .nojekyll file
        run: |
          if [ -d "release/wwwroot" ]; then
            touch release/wwwroot/.nojekyll
          else
            touch release/.nojekyll
          fi
        
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages  # Implanta em um branch separado
          folder: release/wwwroot  # Ajuste conforme necessário
          clean: true  # Remove arquivos antigos
